Completed-CSS-Ecommerce-Page
Henry-Nichols/c0321-code-solutions pull request #34
Opened 2021-03-19 06:52 UTC by Henry-Nichols

![image](https://user-images.githubusercontent.com/73201661/111742167-e53bfe80-8844-11eb-8390-5afc12f2f6cd.png)

2021-03-19 17:58 UTC, codingcodymiller requested changes
Hey dude!! A couple of visual fixes needed:
1. Your images are a bit too large and seem to be overlapping each other. You may just need to put more space between them, but you might also need to adjust the size of the images.
2. The background color for the current price is too dark as compared to the example. I would use a color like "peach"

Address these items and push up your changes, and I will take a closer look at this. Make sure you attach an updated screenshot once your work has been updated!

2021-03-21 17:52 UTC, Henry-Nichols commented
![image](https://user-images.githubusercontent.com/73201661/111915436-8092c680-8a33-11eb-803c-3485cf22b87e.png)

2021-03-22 22:07 UTC, codingcodymiller requested changes

2021-03-22 22:07 UTC, codingcodymiller commented on css-ecommerce-page/style.css
> +}
Is this to make the text lighter? This is actually making your content more see-through, this is not the ideal way to do this. You should just change the text color to something lighter

2021-03-22 23:03 UTC, Henry-Nichols commented
![image](https://user-images.githubusercontent.com/73201661/112068973-32abba80-8b28-11eb-876b-a1788d981b1f.png)

2021-03-23 18:15 UTC, codingcodymiller approved these changes
Nice work!!

2021-03-24 14:32 UTC, merged