Completed Javascript-Typing-Tutor
Henry-Nichols/c0321-code-solutions pull request #56
Opened 2021-04-06 16:41 UTC by Henry-Nichols

![Screen Shot 2021-04-06 at 9 41 26 AM](https://user-images.githubusercontent.com/73201661/113747473-458fc480-96bc-11eb-883b-e6b1c16bc174.png)

2021-04-06 17:13 UTC, codingcodymiller requested changes
Great start here, man!! A couple notes for you:

2021-04-06 17:13 UTC, codingcodymiller commented on javascript-typing-tutor/main.js
> +var arr = typer.textContent.split('');
You can store the phrase in a variable here in javascript, and just generate the spans and append when the page loads, so you don't need to get your data from an HTML element before you can do the work you want to do.

2021-04-06 17:13 UTC, codingcodymiller commented on javascript-typing-tutor/main.js
> +    }
You shouldn't need to destroy all elements and rebuild them every time a letter is typed. Instead, when you generate your array of spans when the page loads, you should append those to the DOM right away and just update the class list on the current letter whenever the user types.

2021-04-06 17:13 UTC, codingcodymiller commented on javascript-typing-tutor/main.js
> +})
You should **_never_** use `location.reload`. It entirely refreshes the page, so the whole page needs to get built again from scratch, which is highly inefficient. Rather, if somebody wants to play again, you just remove all the classes from the letters that are already applied, and reset the value of your variable for what `position` the user is at, so they can just play again without needing to refresh.

2021-04-30 23:18 UTC, thebearingedge requested changes

2021-04-30 23:18 UTC, thebearingedge commented on javascript-typing-tutor/main.js
> +restart.addEventListener('click', function(e) {
Please clean up the merge conflict in your JS and then add, commit, and push again.

2021-04-30 23:43 UTC, thebearingedge approved these changes
Stylish!

2021-04-30 23:43 UTC, Henry-Nichols commented
> Stylish!

Thank you Tim!

2021-04-30 23:43 UTC, merged